---
apiVersion: v1
kind: Pod
metadata:
  name: network-test-debugger
  namespace: default
spec:
  containers:
    - image: lwsg/debug-server
      imagePullPolicy: PullIfNotPresent
      name: debug-server
  restartPolicy: Always
