---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hpa-test
  name: notices
  namespace: default
spec:
  ports:
    - name: hello
      port: 80
      targetPort: 80
  selector:
    app: hpa-test
  clusterIP: 10.6.1.1
  type: ClusterIP
