---
apiVersion: v1
kind: Pod
metadata:
  name: network-test
  namespace: default
spec:
  containers:
    - image: lwsg/notice-server
      imagePullPolicy: PullIfNotPresent
      name: notice-server
      ports:
        - containerPort: 80
          protocol: TCP
      env:
        - name: _NOTICE
          value: |
            1
    - image: lwsg/debug-server
      imagePullPolicy: PullIfNotPresent
      name: debug-server
  restartPolicy: Always

# 2.b 同一 pod 利用 localhost 通信
