kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-practice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-practice
  template:
    metadata:
      labels:
        app: deploy-practice
    spec:
      containers:
        - name: fileserver
          image: hejingkai/fileserver:latest
          ports:
            - name: p1 # 端口名称
              containerPort: 8080  # 容器端口
          volumeMounts:
            - name: download
              mountPath: /usr/share/files
        - name: downloader
          image: hejingkai/downloader:latest
          ports:
            - name: p2 # 端口名称
              containerPort: 3000  # 容器端口
          volumeMounts:
            - name: download
              mountPath: /data
      volumes: # 定义数据卷
        - name: download # 数据卷名称
          emptyDir: {} # 数据卷类型