---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dns-test
  name: dns-new-world
  namespace: default
spec:
  ports:
    - name: notice
      port: 80
      targetPort: 80
  selector:
    app: new-world
  clusterIP: 10.6.1.2
  type: ClusterIP
