---
apiVersion: v1
kind: Pod
metadata:
  name: dns-network-test-1-1
  namespace: default
  labels:
    app: world
spec:
  containers:
    - image: lwsg/notice-server
      imagePullPolicy: PullIfNotPresent
      name: notice-server
      ports:
        - containerPort: 80
          protocol: TCP
      env:
        - name: _NOTICE
          value: |
             world 2
  restartPolicy: Always
