---
apiVersion: v1
kind: Pod
metadata:
  name: network-test-1
  namespace: default
  labels:
    app: rs-app
spec:
  containers:
    - image: lwsg/notice-server
      imagePullPolicy: PullIfNotPresent
      name: notice-server
      ports:
        - containerPort: 80
          protocol: TCP
      env:
        - name: _NOTICE
          value: |
            hello-rs
  restartPolicy: Always
